# Site settings
name: Facundo Troitero
title: Facundo Troitero | Front End Web Developer
description: Front-end web developer focused on building engaging digital experiences 
url: 
baseurl: ''
email: ftroitero@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:ftroitero@gmail.com
  - title: github
    url: https://github.com/MrFacundo
  - title: linkedin
    url: https://www.linkedin.com/in/facundo-t/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
