# Site settings
name: Facundo Troitero
title: Facundo Troitero | Full Stack Developer
description: Full Stack Developer building things for the web 
url: https://mrfacundo.github.io
baseurl: ''
email: ftroitero@proton.me
cover: https://mrfacundo.github.io/img/og.png
logo: https://mrfacundo.github.io/img/emojis/technologist.png
resume: https://mrfacundo.github.io/resume.pdf
social:
  - title: email
    url: mailto:ftroitero@proton.me
  - title: github
    url: https://github.com/MrFacundo
  - title: linkedin
    url: https://www.linkedin.com/in/facundo-t/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap

picture:
  source: img/
  output: resized_images/
  suppress_warnings: true