name: Deploy Jekyll site to Pages
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install JPT's dependencies
        run: sudo apt-get install libvips-tools
        
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
          
      - name: Install Bundler
        run: gem install bundler -v 2.4.15 --no-document
        
      - name: Bundle Install
        run: bundle install
        
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
        
      - name: Build Jekyll site
        run: bundle exec jekyll build
        
      - name: Verify _site directory
        run: ls -la _site
        
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: List uploaded artifacts
        run: ls -la ${{ github.workspace }}
        
      - name: List artifact directory
        run: ls -la _site
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages